//=============================================================================
// Comuns Pixi Filters
//=============================================================================

/*:
 * @target MZ
 * @plugindesc Imports the pixi default filters.
 * @author Comuns
 * @url https://github.com/comuns-rpgmaker
 * 
 * @help Comuns Pixi Filters
 * 
 * This plugin just imports the pixi default filters.
 *
 * pixi-filters - v3.1.1
 * Compiled Thu, 10 Sep 2020 09:58:02 UTC
 *
 * pixi-filters is licensed under the MIT License.
 * http://www.opensource.org/licenses/mit-license
 * 
 */

//=============================================================================
// ** NOTICE **
//-----------------------------------------------------------------------------
// The code below is generated by a compiler, and is not well suited for human
// reading. If you are interested on the source code, please take a look at
// the Github repository for this plugin!
//=============================================================================
